export const  SEARCH_MOVIE = "SEARCH_MOVIE";
export const FETCH_MOVIES = "FETCH_MOVIES";
export const FETCH_MOVIE = "FETCH_MOVIE";
export const LOADING = "LOADING ";
export const ADD_TO_FAVORITE = "ADD_TO_FAVORITE";
export const ADD_TO_FAVORITE_ID = "ADD_TO_FAVORITE_ID";
export const REMOVE_FROM_FAVORITE = "REMOVE_FROM_FAVORITE";